### ISSUE TITLE
Create a README file for Circuits

### ISSUE THREAD

**Issue by VishnuChebolu** [Robotics-Club-BMU/Ardutronics#10]
Hi,
Create a readme file for circuits include its description and table of contents that have title , link and serial no.

Thanks

**Comment by tb-rules10** [comment]
Assign me with this issue

**Comment by tb-rules10** [comment]
plz unassign me from this

**Comment by tb-rules10** [comment]
Can i myself add some ss of arudino circuits in the circuit folder so that they can be made accessible from readme?

**Comment by honeybhardwaj** [comment]
> Can i myself add some ss of arudino circuits in the circuit folder so that they can be made accessible from readme?

can you elaborate please.

**Comment by honeybhardwaj** [comment]
@tb-rules10 no need just have the table empty
