### ISSUE TITLE
Blinking LED

### ISSUE THREAD

**Issue by VishnuChebolu** [Robotics-Club-BMU/Ardutronics#12]
Make a small project with arduino, in which the microcontroller controlls the blinking of a LED.
Definitely, you can use one or more LED's depending upon ur idea.

After, completing the project, create a folder named "BLINKING LED" and push the code with a README file explaining code, circuit and details about it

**Comment by anmolj7** [comment]
Assign me this issue!

**Comment by tb-rules10** [comment]
Assign me this issue

**Comment by VishnuChebolu** [comment]
> Assign me this issue!

Assigned! 
All the best for your first contribution in RWOC

**Comment by anmolj7** [comment]
Do we have to make the blinking led folder in the projects branch? @VishnuChebolu

**Comment by VishnuChebolu** [comment]
yes @anmolj7 .
Make sure that README file should be made with point to point explanation.
