### ISSUE TITLE
Traffic Light Controller

### ISSUE THREAD

**Issue by VishnuChebolu** [Robotics-Club-BMU/Ardutronics#14]
The traffic light controller uses a red, yellow, and green LED to re-create a traffic light on your breadboard. It's an easy way to get hands-on with writing and editing code

**Comment by anmolj7** [comment]
Assign me this issue!

**Comment by anmolj7** [comment]
yes sure :) I will make sure to choose a tough one!

**Comment by VishnuChebolu** [comment]
yes
