### ISSUE TITLE
Create a Blog on Types of arduino

### ISSUE THREAD

**Issue by honeybhardwaj** [Robotics-Club-BMU/Ardutronics#2]
Hi,
Investigate on different types of arduino and create a blog on DEV plaform . once you are over with it update it over readme file.

Thanks

**Comment by anou1234** [comment]
plz assign me this issue!!

**Comment by anou1234** [comment]
plz assign me this issue

**Comment by honeybhardwaj** [comment]
assigned u can work on it

**Comment by anou1234** [comment]
thx

**Comment by anou1234** [comment]
where do i hv to post the blog??
