### ISSUE TITLE
Create a README file for Projects

### ISSUE THREAD

**Issue by VishnuChebolu** [Robotics-Club-BMU/Ardutronics#4]
Hi,
Create a readme file of projects include its description and table of contents that have title , link and serial no.

Thanks

**Comment by anmolj7** [comment]
I would like to work on this issue!

**Comment by tb-rules10** [comment]
@anmolj7 if you could hand this over to me coz i have already made the readme?

**Comment by tb-rules10** [comment]
Otherwise also np

**Comment by VishnuChebolu** [comment]
i will assign to anmol first as it is firstcome and first serve,
it he wants to give to you, I'll assign you @tb-rules10

**Comment by anmolj7** [comment]
I guess it's fine! @tb-rules10 If he has already done the work, he might as well upload it!!
