### ISSUE TITLE
Create a README file for Scripts

### ISSUE THREAD

**Issue by VishnuChebolu** [Robotics-Club-BMU/Ardutronics#6]
Hi,
Create a readme file of scripts include its description and table of contents that have title , link and serial no.

Thanks

**Comment by VishnuChebolu** [comment]
Go ahead!
Assigned.

**Comment by anmolj7** [comment]
I would like to work on this issue!

**Comment by VishnuChebolu** [comment]
you just need to write about script give an example and write the steps to upload files in to scripts with pictures and steps
